### ISSUE TITLE
Sound is broken if 767 is not installed

### ISSUE THREAD

**Issue by sanhozay** [IAHM-COL/727-230#13]
Sounds/sounds.xml is referring to sound files in Aircraft/767.

**Comment by IAHM-COL** [comment]
Thanks
I  am assigning this to myself :)
IH-COL

**Comment by IAHM-COL** [comment]
Fixed in https://github.com/IAHM-COL/727-230/commit/adf6b31b45c4a8335d8293e19f09de137a4414db

IH-COL
