### ISSUE TITLE
Passenger Windows

### ISSUE THREAD

**Issue by IAHM-COL** [IAHM-COL/727-230#5]
The passenger windows could deal with a lot of improvement

For what Ive seen in several pictures, their location is not accurate over the fuselage. Also, they are an additional shiny object that floats above the fuselage object, without touching it, and in certains areas it even leaves spaces evident on zooming

Maybe these should be cut into the fuselage instead, and create windows with glass effect (more like the cockpit's glass)

In addition, maybe adding the good ALS reflection effects, and rain and stuff to all windows of this plane could be a cute enhancement.

@IAHM-COL

**Comment by Pakistan-1** [comment]
It will also be cute to add in a cabin XD

**Comment by IAHM-COL** [comment]
fixed with 844e0a981ce232d7d4afd5a26397b9c6f6a315e2
